ImsV3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ims.urls')),
    path('account/', include('account.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ims/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.branchDasboard, name='index'),
    path('branchdash/<str:pk>/', views.dashboard, name='branchdash'),
    path('dashboard/', views.staffDashboard, name='dashboard'),
    path('update_cart/', views.updateCart, name='update_cart'),
    path('update_quantity/', views.updateQuantity, name='update_quantity'),
    path('cart/', views.cart, name='cart'),
    path('completed/<int:pk>/', views.sale_complete, name='completed'),
    path('checkout/', views.checkout, name='checkout'),
    path('category_list/', views.category_list, name='category_list'),
    path('category/<str:pk>/', views.category, name='category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('reciept/<str:pk>/', views.reciept, name='reciept'),
    path('category_delete/', views.delete_category, name='category_delete'),
    path('branchstore/', views.branchStore, name='branchstore'),
    path('store/', views.store, name='store'),
    path('delete_product/', views.delete_product, name='delete_product'),
    path('sales/', views.sales, name='sales'),
    path('sales<int:pk>/', views.sales, name='sales_single'),
    path('sales_delete/', views.sale_delete, name='sales_delete'),
    path('records/', views.record, name='records'),
    path('products/', views.product_category, name='products'),
    path('product/<str:pk>/', views.product, name='product'),
    path('edit_product/', views.edit_product, name='edit_product'),
    path('set_reorder/', views.edit_inventory, name='set_reorder'),
    path('inventorys/', views.inventory_list, name='inventorys'),
    path('branchinv/', views.branchInventory, name='branchinv'),
    path('delete_inventory/', views.delete_inventory, name='delete_inventory'),
    path('staff/', views.staffs, name='staff'),
    path('staff_detail/<str:pk>/', views.staff, name='staff_detail'),
    path('edit_staff/', views.edit_staff, name='edit_staff'),
    path('delete_staff/', views.delete_staff, name='delete_staff'),
    path('restock/', views.restock, name='restock'),
    path('adminrestock/', views.adminRestock, name='adminrestock'),
    path('export_sales', views.export_sales_csv, name= 'export_sales'),
    path('export_profit/<str:pk>/', views.export_profit_csv, name= 'export_profit'),
    path('export_audit/<str:pk>/', views.export_audit_csv, name= 'export_audit'),
    path('profitData/<str:pk>/', views.profitData, name='profitData'),
    path('branchaudit/', views.branchAudit, name='branchaudit'),
    path('price_audit/<str:pk>/', views.inventoryAudit, name='price_audit'),
    path('ticket/', views.errorTicket, name='ticket'),
    path('create_ticket/', views.createTicket, name='create_ticket'),
    path('tickets/<str:pk>', views.Ticket, name='tickets'),
    path('branchrep/', views.branchReport, name='branchrep'),
    path('reports/<str:pk>', views.report, name='reports'),
    path('branchcount/', views.branchCount, name='branchcount'),
    path('count/', views.countView, name='count'),
    path('admincount/<str:pk>/', views.adminCountView, name='admincount'),
    path('addcount/', views.addCount, name='addcount'),
    path('productlist/<str:pk>/', views.inventoryView, name='productlist'),
    path('sale-pdf/', views.sale_pdf, name='sale-pdf'),
]
# watch out if the value of the variance changes or it is stamped to each date
# what happens when users logs in to another POS and makes sale note: should not be possible

ims/models.py
from datetime import date
from django.db import models
from account.models import CustomUser, Pos, Branch
from simple_history.models import HistoricalRecords


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=200, unique=True)
    last_updated = models.DateField(auto_now=True,)
    date_created = models.DateTimeField(auto_now_add=True,)

    class Meta:
        verbose_name_plural = "categories"
    
    def __str__(self):
        return self.category_name

class Product(models.Model):
    product_name = models.CharField(max_length=150, blank=True, null=True, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.CharField(max_length=150, blank=True, null=True)
    product_code = models.CharField(max_length=100)
    batch_no = models.CharField(max_length=20, blank=True, null=True)
    unit = models.CharField(max_length=50, blank=True, null=True)
    last_updated = models.DateField(auto_now=True,)
    date_created = models.DateTimeField(auto_now_add=True,)
    profit = models.FloatField(blank=True, null=True)
    
    def __str__(self):
        return self.product_name

class Inventory(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='products')
    quantity = models.IntegerField(default=0)
    quantity_available = models.IntegerField(default=0)
    reorder_level = models.IntegerField(default=0, blank=True, null=False)
    choices = (
        ('Available', 'Item is currently available'),
        ('Restocking', 'Currently out of stock'),
    )
    status = models.CharField(max_length=20, choices=choices, default="Available", blank=True, null=True)
    cost_price = models.FloatField(blank=True, null=True)
    sale_price = models.FloatField(blank=True, null=True)
    quantity_restocked = models.IntegerField(default=0, blank=True, null=True)
    count = models.IntegerField(default=0, blank=True, null=True)
    store = models.IntegerField(default=0)
    sold = models.IntegerField(default=0, blank=True, null=True)
    variance = models.IntegerField(default=0)
    available = models.IntegerField(default=0, blank=True, null=True)
    last_updated = models.DateField(auto_now=True,)
    date_created = models.DateTimeField(auto_now_add=True,)
    history = HistoricalRecords()
    
    class Meta:
        verbose_name_plural = "inventories"
        

    def __str__(self):
        return self.product.product_name

    @property
    def store_quantity(self):
        salesitem = self.salesitem_set.all()
        store = self.quantity - sum([item.quantity for item in salesitem])
        return store

    @property
    def quantity_sold(self):
        salesitem = self.salesitem_set.all()
        sold = sum([item.quantity for item in salesitem])
        return sold


class Sale(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    staff = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True)
    total_profit = models.FloatField(default=0, blank=True, null=True)
    final_total_price = models.FloatField(default=0, blank=True, null=True)
    discount =  models.FloatField(default=0, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    date_updated = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    transaction_id = models.CharField(max_length=100, null=True)
    choices = (
        ('Cash', 'Cash'),
        ('Transfer', 'Transfer'),
        ('POS', 'POS'),
    )
    method = models.CharField(max_length=50, choices=choices,default="Cash", blank=True, null=True)
    completed = models.BooleanField(default=False)
    history = HistoricalRecords()

    def __str__(self):
        return str(self.transaction_id)

    @property
    def get_cart_total(self):
        salesitem = self.salesitem_set.all()
        total = sum([item.get_total for item in salesitem])
        return total

    @property
    def get_cart_items(self):
        salesitem = self.salesitem_set.all()
        total = sum([item.quantity for item in salesitem])
        return total

    @property
    def get_total_profit(self):
        salesitem = self.salesitem_set.all()
        profit = sum([item.get_profit for item in salesitem])
        return profit
        # display daily profits on the dashboard and on the sales page
        #time based welcome greeting with javascript

    @property
    def get_total_cost_price(self):
        salesitem = self.salesitem_set.all()
        cost_price = sum([item.get_cost_total for item in salesitem])
        return cost_price


class SalesItem(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    inventory = models.ForeignKey(Inventory, on_delete=models.SET_NULL, blank=True, null=True)
    sale = models.ForeignKey(Sale, on_delete=models.SET_NULL, blank=True, null=True)
    total = models.FloatField(default=0)
    cost_total = models.FloatField(default=0)
    quantity = models.IntegerField(default=0, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True, null=True)
    history = HistoricalRecords()
    
    def __str__(self):
        return str(self.inventory)
    
    @property
    def get_total(self):
        total = self.inventory.sale_price * self.quantity
        return total

    @property
    def get_cost_total(self):
        total = self.inventory.cost_price * self.quantity
        return total

    @property
    def get_profit(self):
        profit = self.get_total - self.get_cost_total
        return profit

class Supplier(models.Model):
    supplier_name = models.CharField(max_length=250, blank=True, null=True)
    supplier_number = models.CharField(max_length=100, blank=True, null=True)
    supplies = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.supplier_name

class ErrorTicket(models.Model):
    staff = models.ForeignKey(Pos, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=150, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    choices = (
        ('Pending', 'Pending'),
        ('Seen', 'Seen'),
    )
    status = models.CharField(max_length=50, choices=choices,default="Pending", blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    date_updated = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return str(self.title)

ims/forms.py
from django.forms import ModelForm, ValidationError
from django import forms
from django.contrib.auth.forms import UserCreationForm
from account.models import CustomUser
from . models import *
from account.models import Branch

class UserCreateForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = (
            'username', 'password1', 'password2', 'is_admin', 'is_sub_admin', 'is_work_staff', 'branch', 'pos'
            )

        widgets = {
            'branch' : forms.Select(attrs={'class':'form-select form-control', 'placeholder':'brabch'}),
            'pos': forms.Select(attrs={'class':'form-control', 'placeholder':'Pos'})
        }


class UserEditForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'is_admin', 'is_sub_admin', 'is_work_staff', 'branch', 'pos')

        widgets = {
            'branch' : forms.Select(attrs={'class':'form-select', 'placeholder':'brabch'}),
            'pos': forms.Select(attrs={'class':'form-select', 'placeholder':'Pos'})
        }

class UserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'phone_number', 'address')

class ProductForm(ModelForm):
    class Meta:
       model = Product
       fields = ('product_name', 'category', 'brand', 'unit', 'batch_no')

       def __init__(self, *args, **kwargs):
           super(ProductForm, self).__init__(*args, **kwargs)
           self.fields['product_name'].widget.attrs['class'] = 'input'
           self.fields['category'].widget.attrs['class'] = 'select'
           self.fields['brand'].widget.attrs['class'] = 'input'
           self.fields['unit'].widget.attrs['class'] = 'input'
           self.fields['batch_no'].widget.attrs['class'] = 'input'
       
       widgets = {
           'category': forms.Select(attrs={'class':'form-select'})
        }

    def clean(self):
        super(ProductForm, self).clean()

        product_name = self.cleaned_data.get('product_name')
        for product in Product.objects.all():
            if product.product_name == product_name:
                self._errors['product_name'] = self.error_class([
                'The product you tried to create already exists'])

        return self.cleaned_data   

class EditProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'category', 'brand', 'unit', 'batch_no',)

        def __init__(self, *args, **kwargs):
           super(ProductForm, self).__init__(*args, **kwargs)
           self.fields['product_name'].widget.attrs['class'] = 'input'
           self.fields['category'].widget.attrs['class'] = 'select'
           self.fields['brand'].widget.attrs['class'] = 'input'
           self.fields['unit'].widget.attrs['class'] = 'input'
           self.fields['batch_no'].widget.attrs['class'] = 'input'

        # widget = {
        #     'product_name' : forms.TextInput(attrs={'class':'form-control', 'placeholder':'Product'}),
        #     'category' : forms.Select(attrs={'class':'form-select form-control', 'placeholder':'Category'}),
        #     'brand': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Brand'}),
        #     'unit': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Unit'}),
        #     'batch_no': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Batch No'})
        # }

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ('category_name',)

    def clean(self):
        super(CategoryForm, self).clean()

        category_name = self.cleaned_data.get('category_name')

        for category in Category.objects.all():
            if category.category_name == category_name:
                self._errors['category_name'] = self.error_class([
                'The category you tried to create already exists'])

        return self.cleaned_data   

class EditCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ('category_name',)

class CreateInventoryForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ('product', 'quantity', 'cost_price', 'sale_price', 'reorder_level')


        widgets = {
                'product': forms.Select(attrs={'class':'form-control form-select'})
            }


    # def clean(self):
    #     super(CreateInventoryForm, self).clean()

    #     product = self.cleaned_data.get('product')

    #     for inventory in Inventory.objects.all():
    #         if inventory.product.product_name == product.product_name:
    #             self._errors['product'] = self.error_class([
    #             'The inventory you tried to create already exists'])

    #     return self.cleaned_data 
    

class AdminCreateInventoryForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ('product', 'branch', 'quantity', 'cost_price', 'sale_price', 'reorder_level')


        widgets = {
                'product': forms.Select(attrs={'class':'form-select'}),
                'branch': forms.Select(attrs={'class':'form-select'})
            }  

class AdminRestockForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ('branch', 'quantity_restocked', 'sale_price', 'cost_price')

        widgets = {
                'branch': forms.Select(attrs={'class':'form-select'})
            }
    

class RestockForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ('quantity_restocked', 'sale_price', 'cost_price')

class ReorderForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ('reorder_level',)

class CreateTicketForm(ModelForm):
    class Meta:
        model = ErrorTicket
        fields = ('title', 'description')
        exclude = ['staff']

class UpdateTicketForm(ModelForm):
    class Meta:
        model = ErrorTicket
        fields = ('status',)

        widgets = {
            'status': forms.Select(attrs={'class':'form-select', 'placeholder':'status', 'required':True})
        }

class PaymentForm(ModelForm):
    class Meta:
        model = Sale
        fields = ('method',)

class AddCountForm(ModelForm):
    class Meta:
        model = Inventory
        fields = ('count',)

templates/ims/add_category.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="addCategoryModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="addCategoryModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h6 class="modal-title" id="addCategoryModalLabel">{% block modal-title %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Add Category{% endblock modal-title %}</h6>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <!--Forms begins-->
      <form {% block Action %} action="{% url 'category_list' %}" {% endblock Action %} method="POST" class="card p-3 border-dark mt-3" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="modal-body">

        <!--==Block Id==-->
        {% block Value-id %}  {% endblock Value-id %}

          <div class="mb-3">
            <label for="category_name" class="form-label">Name</label>
            <input name="category_name" type="text" class="form-control" placeholder="Category Name" required {% block Value-category_name %} {% endblock Value-category_name %}>
            <div class="m-3" style="color:red;">{{form.category_name.errors}}</div>
          </div>

          <div class="mt-4 text-center" style="width:100%;">
            <button type="submit" class="btn btn-secondary">
              {% block Btn-action %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Add Category{% endblock Btn-action %}
            </button>
            
            <button type="reset" class="btn btn-secondary" title="Reset">
              <i class="fas fa-sync-alt"></i>
            </button>
          </div>
        </div>
      </form>
      <!--Form ends-->
    </div>
  </div>
</div>

templates/ims/add_count.html
<div class="modal fade" {% block modal-id %} id="addCountModal{{inventory.pk}}" {% endblock modal-id %} tabindex="-1" aria-labelledby="addCountModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
          <h6 class="modal-title" id="addCountModalLabel">{% block modal-title %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Add Count{% endblock modal-title %}</h6>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <!--Forms begins-->
          <form {% block Action %} action="{% url 'addcount' %}" {% endblock Action %} method="POST" class="card p-3 border-dark mt-3" enctype="multipart/form-data">
          {% csrf_token %}
  
              <div class="modal-body">
                  {% block Value-id %}
                  <div class="input-group mb-3">
                      {% comment %} <span class="side-label btn border-secondary bg-light"><i class="fas fa-key"></i></span> {% endcomment %}
                      <input type="hidden" class="form-control" name="id" value="{{inventory.id}}" readonly>
                  </div>
                  {% endblock Value-id %}

                  {% block Value-count %}
                  <div class="mb-3">
                      <label for="count" class="form-label">Quantity</label>
                      <input type="text" class="form-control" id="count" name="count"  value="{{inventory.count}}">
                  </div>
                  {% endblock Value-count %}


                  <div class="mt-4 text-center" style="width:100%;">
                      <button type="submit" class="btn btn-secondary">
                      {% block Btn-action %}<i class="fa-solid fa-floppy-disk"></i>&nbsp;&nbsp; Save{% endblock Btn-action %}
                      </button>
                      
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>
<script>
  const formsInInput = document.querySelector('#count');
      
  console.log(formsInInput.value);

  formsInInput.value = '';

</script>

templates/ims/add_staff.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="addStaffModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="addStaffModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title" id="addStaffModalLabel">{% block modal-title %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Add Staff{% endblock modal-title %}</h6>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <!--Forms begins-->
        <form {% block Action %} action="{% url 'staff' %}" {% endblock Action %} method="POST" class="card p-3 border-dark mt-3" enctype="multipart/form-data">
          {% csrf_token %}
  
          <div class="modal-body">
  
          <!--==Block Id==-->
          {% block Value-id %}  {% endblock Value-id %}
  
            <div class="mb-3">
              <label for="username" class="form-label">Username</label>
              <input name="username" type="text" class="form-control" placeholder="Username" required {% block Value-username %} {% endblock Value-username %}>
              {% comment %} <div class="m-3" style="color:red;">{{form.username.errors}}</div> {% endcomment %}
            </div>
  
            <div class="mb-3">
              <label for="password1" class="form-label">Password</label>
              <input name="password1" type="password" class="form-control" placeholder="Enter Password" required {% block Value-password1 %} {% endblock Value-password1 %}>
            </div>
            <div class="mb-3">
              <label for="password2" class="form-label">Confirm Password</label>
              <input name="password2" type="password" class="form-control" placeholder="Confirm Password" required {% block Value-password2 %} {% endblock Value-password2 %}>
            </div>
            <div class="mb-3">
              <label for="branch" class="form-label">Branch</label>
              {{form.branch}}
            </div>
            <div class="mb-3">
              <label for="branch" class="form-label">Pos</label>
              {{form.pos}}
            </div>
  
            {% comment %} <div class="mb-3">
              <label for="first_name" class="form-label">First Name</label>
              <input name="first_name" type="text" class="form-control" placeholder="first name" required {% block Value-first_name %} {% endblock Value-first_name %}>
            </div>

            <div class="mb-3">
              <label for="last_name" class="form-label">Last Name</label>
              <input name="last_name" type="text" class="form-control" placeholder="last name" required {% block Value-last_name %} {% endblock Value-last_name %}>
            </div>

            <div class="mb-3">
              <label for="email" class="form-label">Email</label>
              <input name="email" type="email" class="form-control" placeholder="email" required {% block Value-email %} {% endblock Value-email %}>
            </div>

            <div class="mb-3">
              <label for="phone_number" class="form-label">Phone Number</label>
              <input name="phone_number" type="text" class="form-control" placeholder="phone" required {% block Value-phone_number %} {% endblock Value-phone_number %}>
            </div>

            <div class="mb-3">
              <label for="address" class="form-label">Address</label>
              <input name="address" type="text" class="form-control" placeholder="address" required {% block Value-address %} {% endblock Value-address %}>
            </div> {% endcomment %}

            <div class="form-check form-check-inline mb-3">
              <input name="is_admin" class="form-check-input" type="checkbox" id="inlineCheckbox1"  {% block Value-is_admin %} {% endblock %}>
              <label for="is_admin" class="form-check-label" for="inlineCheckbox1">Admin</label>
            </div>
            <div class="form-check form-check-inline mb-3">
              <input name="is_sub_admin" class="form-check-input" type="checkbox" id="inlineCheckbox2"  {% block Value-is_sub_admin %} {% endblock %}>
              <label for="is_sub_admin" class="form-check-label" for="inlineCheckbox1">Sub Admin</label>
            </div>
            <div class="form-check form-check-inline mb-3">
              <input name="is_work_staff" class="form-check-input" type="checkbox" id="inlineCheckbox3"  {% block Value-is_work_staff %} {% endblock %}>
              <label for="is_work_staff" class="form-check-label" for="inlineCheckbox1">Staff</label>
            </div>
            
            <div class="mt-4 text-center" style="width:100%;">
              <button type="submit" class="btn btn-secondary">
                {% block Btn-action %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Add Staff{% endblock Btn-action %}
              </button>
              
              <button type="reset" class="btn btn-secondary" title="Reset">
                <i class="fas fa-sync-alt"></i>
              </button>
            </div>
          </div>
        </div>
        </form>
        <!--Form ends-->
      </div>
    </div>
  </div>
  

templates/ims/admin_add_inventory.html
<!-- Modal -->
<div class="modal fade" {% block modal-id %} id="adminAddInventoryModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="adminAddInventoryModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h6 class="modal-title" id="adminAddInventoryModalLabel">{% block modal-title %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Create Inventory{% endblock modal-title %}</h6>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <!--Forms begins-->
        <form {% block Action %} action="{% url 'branchinv' %}" {% endblock Action %} method="POST" class="card p-3 border-dark mt-3" enctype="multipart/form-data">
          {% csrf_token %}
  
          <div class="modal-body">
  
          <!--==Block Id==-->
          {% block Value-id %}  {% endblock Value-id %}
  
          <div class="mb-3">
            <label for="product" class="form-label">Product</label>
            <select id="id_product" name="product" class="form-select form-select-sm rounded-0" required {% block Value-product %} {% endblock Value-product %}>
            {% if not inventory.product %}
            <option value="" disabled selected>Select Product</option>
            {% else %}
            <option value="" disabled></option>
            {% endif %}
            {% for product in product %}
                {% if inventory.product == product.id %}
                <option value="{{ product.id }}" selected>{{ product.product_name }}</option>
                {% else %}
                <option value="{{ product.id }}">{{ product.product_name }}</option>
                {% endif %}
            {% endfor %}
            </select>
            <div class="m-3" style="color:red;">{{form.product.errors}}</div>
          </div>

            <div class="mb-3">
                <label for="branch" class="form-label">Branch</label>
                {{form.branch}}
                <div class="m-3" style="color:red;">{{form.product.errors}}</div>
            </div>
  
            <div class="mb-3">
              <label for="quantity" class="form-label">Quantity</label>
              <input name="quantity" type="text" class="form-control" placeholder="Quantity" required {% block Value-quantity %} {% endblock Value-quantity %}>
            </div>
  
            <div class=" mb-3">
              <label for="cost_price" class="form-label">Cost Price</label>
              <input name="cost_price" type="text" class="form-control" placeholder="Cost Price" required {% block Value-cost_price %} {% endblock Value-cost_price %}>
            </div>
  
            <div class="mb-3">
              <label for="sale_price" class="form-label">Sale Price</label>
              <input name="sale_price" type="text" class="form-control" placeholder="Sale Price" required {% block Value-sale_price %} {% endblock Value-sale_price %}>
            </div>
  
            <div class="mb-3">
              <label for="reorder_level" class="form-label">Reorder Level</label>
              <input name="reorder_level" type="text" class="form-control" placeholder="Reorder Level" {% block Value-reorder_level %} {% endblock Value-reorder_level %}>
            </div>
  
            <div class="mt-4 text-center" style="width:100%;">
              <button type="submit" class="btn btn-secondary">
                {% block Btn-action %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Create Inventory{% endblock Btn-action %}
              </button>
              
              <button type="reset" class="btn btn-secondary" title="Reset">
                <i class="fas fa-sync-alt"></i>
              </button>
            </div>
          </div>
        </form>
        <!--Form ends-->
      </div>
    </div>
  </div>

templates/ims/cost_price.html
{% block content %}

<div class="modal fade" {% block modal-id %} id="addCostPriceModal" {% endblock modal-id %} tabindex="-1" aria-labelledby="addCostPriceModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h6 class="modal-title" id="addCostPriceModalLabel">{% block modal-title %}<i class="fas fa-plus"></i>&nbsp;&nbsp; Cost Price{% endblock modal-title %}</h6>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <!--Forms begins-->
            <form {% block Action %} action="" {% endblock Action %} method="POST" class="card p-3 border-dark mt-3" enctype="multipart/form-data">
            {% csrf_token %}
    
                <div class="modal-body">

                    <div class="input-group mb-3">
                        <input type="text" class="form-control" name="cost_price"  value="{{products.cost_price}}">
                    </div>
                    <div class="mt-4 text-center" style="width:100%;">
                        <button type="submit" class="btn btn-secondary">
                        {% block Btn-action %}<i class="fa-solid fa-floppy-disk"></i>&nbsp;&nbsp; Save{% endblock Btn-action %}
                        </button>
                        
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}